/** Approach page — a deliberate four-stage narrative designed around practical change. */
import { MoveRight } from "lucide-react";
import { Link } from "wouter";
import { PageEyebrow, SiteShell } from "@/components/SiteShell";

const steps = [["I", "Listen closely", "Begin with the question beneath the surface: what is affecting service, team confidence, safety, or guest trust?"], ["II", "See the whole picture", "Connect the client or guest journey with the habits, handovers, procedures, and pressures behind it."], ["III", "Shape the practical path", "Translate insight into clear priorities, usable recommendations, focused coaching, or more consistent standards."], ["IV", "Embed what improves", "Design the work to last within real shifts, real teams, and the daily rhythm of the business."]];

export default function Approach() {
  return <SiteShell tone="dark"><main><section className="approach-hero"><div className="approach-hero__image"><img src="/manus-storage/trustcore-advisory-workspace_0516e71b.jpg" alt="Hospitality professionals in an operational discussion" /></div><div className="page-shell approach-hero__inner motion-reveal"><PageEyebrow chapter="03">The approach</PageEyebrow><h1>Practical change begins with a <em>clearer view.</em></h1><p>Considered enough to understand the real context. Clear enough to put into practice on the next shift.</p></div></section><section className="approach-path"><div className="page-shell"><div className="approach-path__intro motion-reveal"><PageEyebrow chapter="A">The working method</PageEyebrow><p>The work moves from attention to action without losing sight of the people who will carry it forward.</p></div><div className="approach-steps">{steps.map(([number, title, detail], index) => <article className="approach-step motion-reveal" style={{ transitionDelay: `${index * 90}ms` }} key={number}><span>{number}</span><div><h2>{title}</h2><p>{detail}</p></div><i /></article>)}</div></div></section><section className="approach-quote"><div className="page-shell motion-reveal"><p>“Good advisory work should create clarity without adding complexity.”</p><span>Eva Kyriakou</span></div></section><section className="closing-link closing-link--dark page-shell motion-reveal"><p>Bring the operating question that is already asking for attention.</p><Link href="/contact" className="text-link">Start a conversation <MoveRight /></Link></section></main></SiteShell>;
}
